// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: ra.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromId        int32                  `protobuf:"varint,1,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`
	Timestamp     int32                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestMsg) Reset() {
	*x = RequestMsg{}
	mi := &file_ra_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestMsg) ProtoMessage() {}

func (x *RequestMsg) ProtoReflect() protoreflect.Message {
	mi := &file_ra_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestMsg.ProtoReflect.Descriptor instead.
func (*RequestMsg) Descriptor() ([]byte, []int) {
	return file_ra_proto_rawDescGZIP(), []int{0}
}

func (x *RequestMsg) GetFromId() int32 {
	if x != nil {
		return x.FromId
	}
	return 0
}

func (x *RequestMsg) GetTimestamp() int32 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type ReplyMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromId        int32                  `protobuf:"varint,1,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplyMsg) Reset() {
	*x = ReplyMsg{}
	mi := &file_ra_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyMsg) ProtoMessage() {}

func (x *ReplyMsg) ProtoReflect() protoreflect.Message {
	mi := &file_ra_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyMsg.ProtoReflect.Descriptor instead.
func (*ReplyMsg) Descriptor() ([]byte, []int) {
	return file_ra_proto_rawDescGZIP(), []int{1}
}

func (x *ReplyMsg) GetFromId() int32 {
	if x != nil {
		return x.FromId
	}
	return 0
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_ra_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_ra_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_ra_proto_rawDescGZIP(), []int{2}
}

var File_ra_proto protoreflect.FileDescriptor

const file_ra_proto_rawDesc = "" +
	"\n" +
	"\bra.proto\"C\n" +
	"\n" +
	"RequestMsg\x12\x17\n" +
	"\afrom_id\x18\x01 \x01(\x05R\x06fromId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x05R\ttimestamp\"#\n" +
	"\bReplyMsg\x12\x17\n" +
	"\afrom_id\x18\x01 \x01(\x05R\x06fromId\"\x05\n" +
	"\x03Ack2?\n" +
	"\x05Mutex\x12\x1c\n" +
	"\aRequest\x12\v.RequestMsg\x1a\x04.Ack\x12\x18\n" +
	"\x05Reply\x12\t.ReplyMsg\x1a\x04.AckB\x1cZ\x1aricart-agrawala/grpc/protob\x06proto3"

var (
	file_ra_proto_rawDescOnce sync.Once
	file_ra_proto_rawDescData []byte
)

func file_ra_proto_rawDescGZIP() []byte {
	file_ra_proto_rawDescOnce.Do(func() {
		file_ra_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ra_proto_rawDesc), len(file_ra_proto_rawDesc)))
	})
	return file_ra_proto_rawDescData
}

var file_ra_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_ra_proto_goTypes = []any{
	(*RequestMsg)(nil), // 0: RequestMsg
	(*ReplyMsg)(nil),   // 1: ReplyMsg
	(*Ack)(nil),        // 2: Ack
}
var file_ra_proto_depIdxs = []int32{
	0, // 0: Mutex.Request:input_type -> RequestMsg
	1, // 1: Mutex.Reply:input_type -> ReplyMsg
	2, // 2: Mutex.Request:output_type -> Ack
	2, // 3: Mutex.Reply:output_type -> Ack
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ra_proto_init() }
func file_ra_proto_init() {
	if File_ra_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ra_proto_rawDesc), len(file_ra_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ra_proto_goTypes,
		DependencyIndexes: file_ra_proto_depIdxs,
		MessageInfos:      file_ra_proto_msgTypes,
	}.Build()
	File_ra_proto = out.File
	file_ra_proto_goTypes = nil
	file_ra_proto_depIdxs = nil
}
